### ISSUE TITLE
API - Typo in StoreTypeFactory for loop

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-experimental#100]
I noticed that this for loop is presumably meant to be for **storeType** in storeTypes but is misspelled as **storeTypes** in storeTypes, which makes it a bit confusing to read as everything is plural and the same variable name.

https://github.com/gchq/gaffer-experimental/blob/865d87d261c91c53145100ef0276935525076118/gaffer-as-a-service/gaas-rest/src/main/java/uk/gov/gchq/gaffer/gaas/factories/StoreTypeFactory.java#L37-L45

**Comment by rocky341** [comment]
Now redundant as we don't have StoreTypeFactory anymore
