### ISSUE TITLE
Swap GafferBuilder classes for Helm Value.yaml overrides as configs

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#107]
As a User: I want to add my own Value.yaml overrides 
So that: I can configure my own pre configured custom helm deployments

Deliverable: 
- Instead of having GafferSpec class builders, Users can add their own Values.yaml overrides to a directory that can be read in by GaaS API and then passed to the Gaffer Controller 
- The name of the config is determined by the name of the file (e.g. accumulo-big.yaml will have the config ID 'accumulo-big'), consider logic or add README details that tell the User config names have to be unique
- These Value.yaml override configs are pre set (hardcoded) and multiple can be added to the directory by Technical Users
- These .yamls will be added to the resource directory so Users can easily add as many config as they wish
- The API will take the names of the individual files as the configIds or configNames (e.g. accumulo-big.json = String configName = "accumulo-big")

Additional Info:
Example .yaml override file names and configs will look like these:
- values-federated.yaml https://github.com/gchq/gaffer-docker/blob/develop/kubernetes/gaffer/values-federated.yaml
- values-host-based-ingress.yaml https://github.com/gchq/gaffer-docker/blob/develop/kubernetes/gaffer/values-host-based-ingress.yaml

**Comment by rocky341** [comment]
Hi @r32575,
Currently working on this ticket and have come across an issue to do with schemas. As there is no logic in the API when creating a spec it always adds a schema to the spec. This schema may be empty in for example a federated store however it is still added. E.g:
`
spec:
--graph:
---config:
----description: graph
----graphId: mygraph
---storeProperties:
----gaffer.serialiser.json.modules: uk.gov.gchq.gaffer.sketches.serialisation.json.SketchesJsonModules
----gaffer.store.class: uk.gov.gchq.gaffer.federatedstore.FederatedStore
----gaffer.store.properties.class: uk.gov.gchq.gaffer.federatedstore.FederatedStoreProperties
---schema: {}
`
As opposed to:
`
spec:
--graph:
---config:
----description: graph
----graphId: mygraph
---storeProperties:
----gaffer.serialiser.json.modules: uk.gov.gchq.gaffer.sketches.serialisation.json.SketchesJsonModules
----gaffer.store.class: uk.gov.gchq.gaffer.federatedstore.FederatedStore
----gaffer.store.properties.class: uk.gov.gchq.gaffer.federatedstore.FederatedStoreProperties
` 

Is this an issue or is it okay to include an empty schema in things such as federated stores?

**Comment by t92549** [comment]
@rocky341 Yes this is fine as federated stores have an empty schema
