### ISSUE TITLE
GaaS API knows if config is a Federated Store Config - based on the storeproperties store.class.name set

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#108]
As a User - I want to add all my store configs to the same directory 
So that - I can easily add configs in one go and the API can be smart to distinguish which configs are designed to deploy Federated Store Graphs

Deliverable:
- The GaaS API can determine if a config is designed for a Federated Store as if the storeproperty store class name is set as FederatedStore.class , then the Gaffer Controller will deploy a Federated Store Graph
- This means the GaaS API can be intelligent to check the config if this value is set to FederatedStore.class and can return via the GET `/storeconfigs` or `/storetypes` endpoint which is a federated store config

The response to this endpoint will be amended to: 
```
{ 
   "storeTypes": ["accumuloStore", "accumuloBig"],   // <- example storetype config names
   "federatedStoreTypes": ["federatedStore1", "federatedConfig3"],
}
```

Note:
- If this ticket is started before the value.yaml overrides have been added to replace the Java class builders, then add a new method to the StoreType.class interface that is call `isFederatedConfig()` and hardcode return true or false (this is a simple temporary solution as this will soon be replaced with .yamls) for the API to know if a config is configured for Federated Stores

**Comment by go159lab** [comment]
Hi @r32575 @t92549 

How should Gaas-Rest handle the following scenario?
Given a user provides this invalid config which has invalid key (invalidStoreProperties)
graph:
  invalidStoreProperties:
    gaffer.store.class: uk.gov.gchq.gaffer.mapstore.MapStore
    gaffer.store.job.tracker.enabled: true
    gaffer.cache.service.class: uk.gov.gchq.gaffer.cache.impl.HashMapCacheServic

**Comment by t92549** [comment]
@go159lab I think for now at least, invalid configs should not be checked by the API and just sent straight to the controller where they should either still work or fail if they are really incorrect.

**Comment by t92549** [comment]
@macenturalxl1 I think that after thinking about it more, the knowledge of what a `storeTypes` or `federatedStoreTypes` is should not be assumed. In that case, perhaps all graphs by default are assumed to require a `graphId` and `description`. Anything beyond that should be described in the `/storetypes` endpoint response. For example:
```
{
  "storeTypes": [
    {
      "name": "accumuloSmall",
      "parameters": [
        "schema"
      ]
    },
    {
      "name": "accumuloBig",
      "parameters": [
        "schema"
      ]
    },
    {
      "name": "federated",
      "parameters": [
        "proxies"
      ]
    },
  ]
}
```

This lets the endpoint actually describe to whatever is consuming it, for example the UI, what is needed without them having to already know. This removes assumptions from UI code.

This could be expanded further perhaps to also specify that the `graphId` and `description` are required, but as these will be by all graphs I think this assumption is okay.
