### ISSUE TITLE
UI - The UI can retrieve all the configs that are added to the API config directory and display them in the dropdown box in the Create Graph form

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#109]
As a User of the UI: I want to Create A Graph and select the available pre configured configs the API can deploy
So that: I can make easier deployments with set settings

Deliverable:
- The dropdown will make a call to GET the available configs and return the response noted below
- It can also determine which config option is a '1-store' graph config and which one is federated store from this response
- So that the 'add federated proxy stores' part of the form will be displayed to make the appropriate request by providing the proxy stores the graph will federate
- In the request body when submitting a Create Graph Request, it should provide the graphId, description, schema still - and add a new field store config that will be the name of the config the User has selected from the dropdown
- If the config the User has selected from the dropdown is a federated store type config, then the request should include the ProxyStore values still

Additional Info:
GET /storetypes request
```
{ 
   "storeTypes": ["accumuloStore", "accumuloBig"],   // <- example storetype config names
   "federatedStoreTypes": ["federatedStore1", "federatedConfig3"],
}
```

**Comment by K-itKat20** [comment]
In the process of refactoring the UI to use the stereotypes it receives from the backend. Refactored most components and unit test. main-graph-table-row and gauge still need to be refactored and unit tests updated.


Additionally, the main-graph-table-row component currently uses useEffect to run getStoreTypes() and getAllGraphIds(). This is causing performance issues. One solution, related to #111, is to move the main-graph-table-row component back to view graph.

This work will be done under that ticket, for now this ticket is blocked until that ticket is complete.

**Comment by K-itKat20** [comment]
completed #109, refactored and completed unit tests.
TODO: gauge component in view-graphs

**Comment by K-itKat20** [comment]
Completed gauge and unit tests. Need to merge with develop-ui
