### ISSUE TITLE
UI - convert MainGraphTableRow to a table component instead

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#111]
Fix warning

Currently the tests have a warning that `<tr />` tags should be wrapped in a `<table />` tag

Fix: the warning by moving the Table component in ViewGraphs.tsx in to the `MainGraphTableRow` component - then rename to `MainGraphTable`

**Comment by K-itKat20** [comment]
Refactored view-graphs page to include view-graphs-table and gauge.
