### ISSUE TITLE
API - Gaas-rest Request Body (maintainance)

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#120]
'Code maintenance task'

There are multiple CreateGraphRequest constructors from the previous solution in the way graphs are created from sending HTTP requests

Now the solution is a flexible, whereby a User can specify a graphId, description and configName (used to be called storeType) in the request body to create a graph deployment. I.e.

```
{
   "graphId": "example-graph",
   "description": "This is an example",
   "configName": "accumuloBig"
}
```

Todo:
- Fix the code so there is only one constructor for all
- This requires fixing areas of the code (impl and tests) where the old constructors have been used

**Comment by macenturalxl1** [comment]
Hi @t92549 - what would be the best name for the field in the creategraph request body for a User to declare which available config they want to use?

`configName`, `gafferSpecConfigName`, `gafferConfigName`... any that you think are better/simpler?

```
{
   "graphId": "example-graph",
   "description": "This is an example",
   "configName": "accumuloBig"
}
```

**Comment by t92549** [comment]
I think `configName` is fine
