### ISSUE TITLE
UI - Validation on the GraphId Input box (Create Graph Form)

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#121]
As a User - I want to have clearer consistent validation when entering graph ID
So that - I have faster feedback to correct it

Solution:
- Use the Material UI 'validation error' prop to display what is wrong or the correct format for a graphId
- You can make the graphId string in to a GraphId object, and have a validate() method in the object that the Material UI input onChange calls to check if it is valid
- This validate() can return a string message for the validation to display

**Comment by K-itKat20** [comment]
Completed and merged into develop-ui
