### ISSUE TITLE
Update Gaffer version to 1.17.1

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#129]
[No User Story]

When the next Gaffer release is available (1.17.1), update this in `gaffer-as-a-service` and `gaffer-experimental`

`gaffer-as-a-service`
May not cause any breaking changes

`gaffer-experimental` (top level pom)
May cause some breaking changes as some methods in Gaffer have become deprecated and may cause Checkstyle to fail

**Comment by t92549** [comment]
[Gaffer 1.17.1](https://hub.docker.com/layers/gchq/gaffer/1.17.1/images/sha256-c241f621bbb8b76d3ce3854c3f1c425416b89f8b16708a4451611ee351385d83?context=explore) is now released on dockerhub
