### ISSUE TITLE
Make 'gaas-ui' deployable on a Kubernetes cluster

### ISSUE THREAD

**Issue by t11947** [gchq/gaffer-experimental#18]
Create helm charts and related Kubernetes configuration to allow for current Kai functionality to be wholly deployable on a Kubernetes cluster.

**Comment by d47853** [comment]
This is a high-level ticket which involves:
* A REST API which can receive queries
* A UI which communicates with the REST API
* A backend which carries out requests from the REST API to produce Graphs

**Comment by macenturalxl1** [comment]
The gaas-ui app has a helmchart. It is implemented in this pull request: https://github.com/gchq/gaffer-experimental/pull/39

**Comment by macenturalxl1** [comment]
The GaaS Controller is the back end service that carries out requests from the GaaS Rest API and already has a helmchart in it's directory under `gaffer-controller/deploy/helm/`
