### ISSUE TITLE
Create a kubernetes-deployable version of the Kai REST API

### ISSUE THREAD

**Issue by t11947** [gchq/gaffer-experimental#19]
Currently the Kai REST API is heavily coupled to AWS services. Create a containerisable version that is deployment-agnostic. Technology preference Spring Boot.

**Comment by d47853** [comment]
This high level ticket encompasses #30 #31 and #32

**Comment by b956022** [comment]
Pull request has been raised for review, still working on unit tests in the background.

**Comment by d47853** [comment]
I think it's been reviewed. Does it need another look?
