### ISSUE TITLE
Decouple Kai UI from AWS services

### ISSUE THREAD

**Issue by t11947** [gchq/gaffer-experimental#21]
Create a version of the Kai UI that is decoupled from AWS services - specifically with regards to authentication. A configurable/plugin approach for authentication would be ideal.

**Comment by macenturalxl1** [comment]
Hi - will create a pull request shortly to pull Kai in to this repo. The pull request for that will include this ticket, decoupling it from AWS.

**Comment by d47853** [comment]
Just to be clear, you only mean the UI, correct? We don't want the whole infrastructure side of it pulled into here.

**Comment by b956022** [comment]
Yes just the GUI 👍 writing unit tests now with the ambition of submitting a pull request this week.

**Comment by macenturalxl1** [comment]
Hi just raised the pull request for the UI to be brought in to this project. It is under the directory `gaffer-experimental/gaas-ui/`
