### ISSUE TITLE
Scope controller to single namespace

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-experimental#26]
In order to make the controller more acceptable to cluster admins, we should scope the controller to only be able to manage gaffer deployments within the namespace in which it's deployed.

**Comment by ctas582** [comment]
+1
This would also enable multiple controllers to be deployed in the same cluster, each managing deployments in different namespaces. However, it should still be possible to configure a controller to globally manage deployments across all namespaces.

**Comment by d47853** [comment]
Merged into develop
