### ISSUE TITLE
SLF4J Logger has conflicts, log4j2 is not being used

### ISSUE THREAD

**Issue by GCHQDeveloper314** [gchq/gaffer-experimental#271]
In the next release of Gaffer Log4J is going to be replaced with Reload4J. This will impact any projects which inherit from Gaffer. It appears that `gaas-rest` is currently using logback for logging and not log4j as used by the current releases of Gaffer.

This seems to be because of a dependency which indirectly introduces logback. This can be seen in this SLF4J warning when running tests for `gaas-rest`:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:~/.m2/repository/ch/qos/logback/logback-classic/1.2.9/logback-classic-1.2.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:~/.m2/repository/org/slf4j/slf4j-log4j12/1.7.32/slf4j-log4j12-1.7.32.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
```
This conflict should be resolved because the SLF4J binding which is used is potentially inconsistent: "The way SLF4J picks a binding is determined by the JVM and for all practical purposes should be considered random" - quote from the link in the output above.

In the POM for `gaffer-as-a-service` it looks as though Log4j2 was intended to be used for logging, but as the dependency is placed in `dependencyManagement` instead of being added directly and it is not introduced by any other dependency as a transitive dependency, it ends up not being used at all.

It would probably be best to simplify how logging dependencies are managed by simply using the binding defined by Gaffer. This would require excluding all SLF4J bindings introduced by additional dependencies and any other logging frameworks to prevent a conflict (as seen above).

**Comment by t92549** [comment]
See https://github.com/gchq/Gaffer/pull/2609
