### ISSUE TITLE
Kai UI - Change description to be optional

### ISSUE THREAD

**Issue by K-itKat20** [gchq/gaffer-experimental#272]
In the current create graph page the description field is mandatory, change this to be optional as it is currently not required when creating graphs.

**Comment by t92549** [comment]
The descriptions in the schemas definitely need to be optional. Might need to think more about whether the graph description is optional as I can see an argument as to why it should be mandatory.

**Comment by b956022** [comment]
Agree with @t92549 although its optional in the schema I'm going to say we keep it as mandatory is GaaS as we'd like to know why it was created and for what purpose, thus helping supporting the platform. Closing this ticket now.

**Comment by t92549** [comment]
@b956022 I can understand this for a graph but I think making the description mandatory for a type in the schema is perhaps a little much? A lot of types may end up with descriptions like: "A string".
I also agree though that descriptions will be good for the platform so I am open to whether or not it is needed in this case.
