### ISSUE TITLE
Create folder structure for Gaffer as a Service

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-experimental#30]
At the moment we have the Gaffer controller containing all the code for GaaS as is. To develop the REST API and UI though we would need to put a folder structure in place. I suggest something like:
```
gaffer-as-a-service/
|-- gaas-common/
|    |-- src/
|    |-- pom.xml
|-- gaffer-controller
|    |-- src/
|    |-- pom.xml
|    |-- Dockerfile
|-- gaas-rest
|    |-- src/
|    |-- pom.xml
|    |-- Dockerfile
|-- gaas-ui
|    |-- src/
|    |-- package.json
|    |-- Dockerfile
|-- helm/
|-- pom.xml
```

Where the high-level gaffer-as-a-service just contains dependency management and versions, the common module contains models that can be shared between the REST API and controller, the controller and REST API in it's own modules and then the gaas-ui as a npm project underneath gaffer-as-a-service. The helm charts could live in one place to make things easier to deploy

**Comment by rocky341** [comment]
How would you like this done with regard to existing modules in the project which have not been mentioned on the ticket? Also would you like the root folder to be renamed from "gaffer-experimental" to "gaffer-as-a-service" or would you like "gaffer-as-a-service" to be a module within gaffer-experimental which then contains modules such as gass-rest, haas-ui etc. 

Possible structure: 
gaffer-experimental
| -- gaffer-as-a-service
|        | -- gaas-common   
|        |       | -- src
|        |       | -- pom.xml
|        | -- gaas-rest
|        |        | --src
|        |        | -- pom.xml
|        |       | -- Dockerfile
|        | -- gaas-ui
|        |       | -- src
|        |       | -- pom.xml
|        |       | -- Dockerfile
|        | -- gaffer-controller
|        |       | -- src
|        |       | -- pom.xml
|        |       | -- Dockerfile
| -- tinkerpop   
| -- graffer-ql 
| --  
| -- 


Or alternatively a possible structure could be:
gaffer-as-a-service
| -- gaas-common
|        | -- src
|        | -- pom.xml
| -- gaas-rest 
|        | -- src
|        | -- pom.xml
|        | -- Dockerfile
| -- gaas-ui
|        | -- src
|        | -- pom.xml
|        | -- Dockerfile
| -- gaffer-controller
|        | -- src
|        | -- pom.xml
|        | -- Dockerfile

With then modules such as tinkerpop etc being in a separate repository.

**Comment by r32575** [comment]
@rocky341, for now I think the first option is best while the project is still experimental.

**Comment by rocky341** [comment]
@r32575 Perfect thank you. The structure has been implemented and can raise a pull request however just wanted to double check if you wanted the refactoring done on this ticket or as a separate refactoring process. (With any new shared code being added to gaas-common on an on going basis)

**Comment by r32575** [comment]
@rocky341, I'd include the refactoring under this ticket.
