### ISSUE TITLE
Deploy Graph With Accumulo & Map Store Options

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-experimental#34]
At the moment users can create a Map store fairly easily. If they want to create an accumulo store they need to provide more configuration and would potentially have to provide the Accumulo passwords which would be stored in the Gaffer spec section which isn't particularly secure.

As a user I want to create Accumulo stores but I want the passwords to be stored in a secure way which doesn't show up in the spec.

**Comment by r32575** [comment]
At present, the `value` store is created by the `CreateGraphService.buildCreateCRDRequestBody` and gets passed through as JSON to the `controller`. This is then converted into a `YAML` and stored as a `value.yaml` file on a new `Helm` pod. The `Helm` chart, stored in the `gaffer-controller` `properties` file  can be found here: https://github.com/gchq/gaffer-docker/tree/develop/kubernetes/gaffer. At present you are creating the default `Gaffer` instance with in-memory storage as default. You are just specifying the name of the graph which translates to the following in the `Helm` chart created by the `gaffer-controller`

```
graph:
  config:
    graphId: <graph_name>
```

You can alter the default to create an `accumulo` store by adding to your model so the following is sent:

```
graph:
  config:
    graphId: <graph_name>
accumulo:
  enabled: true
```

At present the standard password is used. This is being looked into.

So your code and Swagger end point will need to be altered  and the UI changed to reflect the choices when creating a graph. There are other types such as the `federated` store so bare this in mind as setting up a `federated` store to federate to your `Gaffer` instances may be required in the future.

**Comment by macenturalxl1** [comment]
See https://github.com/gchq/gaffer-docker/blob/develop/kubernetes/gaffer/values.yaml

**Comment by rocky341** [comment]
As a user if I don't specify a store will it create a map store by default (as is) or do I have to specify if I want to create a map store in the api request?

Same question as above but creating a gaffer instance with accumulo store instead.

If specifying a store is mandatory we will return an error message if none is specified in the request.

**Comment by r32575** [comment]
@rocky341, I would have the store type as a mandatory field for the `gaas-rest` service endpoint. For the UI create graph page, you could have the in-memory store selected as default.
