### ISSUE TITLE
Make 'gaas-rest' REST API deployable via Helm

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-experimental#35]
As a user - I want to be able to deploy the the REST API via helm separately to the controller or alongside it
So that I - can use the REST API to query CRDs

Deliverables:
- Able to 'helm' deploy to a kubernetes cluster with configurable values that connect to the correct specified Kubernetes cluster (possible solution is to use ENV variables)

**Comment by K-itKat20** [comment]
Added helm functionality to gaas-rest, can now be deployed by using Helm.

**Comment by K-itKat20** [comment]
Pull request created #42
