### ISSUE TITLE
Allow the REST API to be able to retrieve namespaces which the gaffer-controller has been deployed within

### ISSUE THREAD

**Issue by d47853** [gchq/gaffer-experimental#36]
As a user I want to know what namespaces I can deploy graphs in via the REST API. If #32 has been done, it would be even better to only return the namespaces which I as a user have access to.

**Comment by go159lab** [comment]
Start working for this ticket.
Added in gaas-rest API retrieve all namespaces functionality and integration test.

**Comment by macenturalxl1** [comment]
Moved to In Review. This feature has been implemented in this https://github.com/gchq/gaffer-experimental/pull/38 Pull Request
