### ISSUE TITLE
Create a Get Cluster Namespaces Page in the UI

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#43]
As a User: I want to use the UI and see all the namespaces available on the cluster
So that: I can see all namespaces available

- In the UI create a component that uses the new 'GET namespaces' endpoint in the REST API and present the namespaces list response in the UI
- List in a table similar to how the Gaffer Graph instances are presented
- This component can be implemented as a new page with it's own route (e.g. [host]/namespaces)

**Comment by K-itKat20** [comment]
Created a cluster-namespaces UI component which shows all of the namespaces in the cluster.
