### ISSUE TITLE
Add Store Type Option To Create Graph Form

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#45]
As a User - when I want to create a Graph I want to customize it with a [Map/Accumulo] store

So that - my Graph can benefit from having a [Map/Accumulo] store

Deliverables:
- On the 'Add Graph' form, include a 'store type' option for Users 
- Map store can be used as default, this means that you can either:
     1. Have Map & Accumulo in a dropdown and have an (i) info icon to advise users that Map is preferable as a default option if Users are unsure 
     2. Or, have Default, Map & Accumulo as 3 options and an (i) icon to say Default is the Map option
     3. Or, better fit solution for friendly UX...

**Comment by K-itKat20** [comment]
Completed and added to #39
