### ISSUE TITLE
Deploy a Graph with a Federated Store

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#49]
As a User - I want to deploy a Federated Store Graph
So that - I can add sub-graphs using the Federated Store feature

**Comment by rocky341** [comment]
User can define a graph backed by a Federated Store. This will pass the default store property overrides relevant to Federated Store to the yaml found here:
https://github.com/gchq/gaffer-docker/blob/develop/kubernetes/gaffer/values-federated.yaml

We have also updated this for the UI ticket.
