### ISSUE TITLE
Disable AddGraph Operation On Fed Store

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#50]
As a User - I want to disable adding additional graphs to my federated store
So that - my fed store is more secure

Solution:
System User (gaas user):
System User can only add stores at run time - unable to send requests from outside cluster

Operation authoriser hook - controls Users can only use cetain operations, lock this down to GaaS System User only

Example of hook to add to the Graph Config:
https://github.com/gchq/Gaffer/blob/develop/core/graph/src/test/resources/opAuthoriser.json

Also see image here - test that this image includes the operation-auth features:
https://hub.docker.com/r/gchq/gaffer-rest

On the values.yaml add e.g:
graph:
  config:
    graphId: "gafferTest"
    hooks:
      - class: "package.class"
      - 

Other (non preferred way)
Steps:
create fed store
add proxy
nullify addgraph handler
turn off/on with 
JCS cache on
Then fed store will turn on with graphs 

Note: To turn off AddGraph requests....
Null the add graph handler at initiation to turn in the operation declaration (null for do not support)
Then turn back on with cached graphs

**Comment by t92549** [comment]
@macenturalxl1 I have emailed you about a meeting to discuss creating federated stores

**Comment by r32575** [comment]
There is a guide on adding jars to the lib directory: https://gchq.github.io/gaffer-docker/kubernetes/docs/add-libraries.html
