### ISSUE TITLE
Fix ui linting

### ISSUE THREAD

**Issue by t92549** [gchq/gaffer-experimental#56]
Currently the linter keeps complaining about `'React' was used before it was defined`, would be nice if this was cleaned up

**Comment by t92549** [comment]
Might be worth adding this is a low priority issue to do with how `typescript-eslint` is setup in the project

**Comment by K-itKat20** [comment]
We've looked at ESLint and added some config options to https://github.com/K-itKat20/gaffer-experimental/blob/gh-56-linting/gaas-ui/.eslintrc.json .
Let us know if these config options are okay and any other options you'd want to be included.

**Comment by t92549** [comment]
The linting changes seem to have cleaned up all the issues that were there before. Changing to double quotes across the code base is fine as long as it is kept consistent. Currently this seems to be the case except the tests which all seem to use single quotes. This is a very minor thing though so sorry to keep bringing it up.

**Comment by rocky341** [comment]
Can make the tests all use double quotes and will then make the pull request.
