### ISSUE TITLE
Graph ID validation fix

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#69]
Fix

Currently the way the Graph ID is being used has multiple conflicting validations:

- Gaffer Graph Library has a regex validation on GraphId of `"[a-zA-Z0-9_]*"` (See GraphLibrary.java in Gaffer)

- kind: Gaffer metadata does not allow underscores, it only allows `"[a-zA-Z0-9-.]*"` (check if this is correct validation) so consider this when setting metadata

- There is some additional validation in create Graph request (might be coming from controller) that only allows `"[a-zA-Z0-9-]*"` (again, check this)

**Comment by rocky341** [comment]
Kubernetes only allows: lower case alphanumeric characters, '-' or '.' 
Controller does some extra validation:
a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name',  or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')
