### ISSUE TITLE
Pipeline Job - Build & Push Docker Image to Docker Hub

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#73]
As a Developer User - when raise a Pull Request for my branch I want a Docker image available to deploy to Kubernetes
So that - it I don't have to do it manually and can easily deploy the latest version

Deliverable:
Add a job that automates the docker build and push of the branch to a Docker hub repo that is stored as a value in the repo's setting's

**Comment by rocky341** [comment]
Need to fix service account issue with current pipeline
