### ISSUE TITLE
Convert Spring 500 Error Response Body to GaaS Error Response Format

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#75]
Currently when a 500 error is returned (e.g. from the API throwing an uncaught exception) - the error returned is a Spring Error Response.

The UI therefore can not handle this Error Response body.

Todo: 
- API: Use the CustomErrorHandler to properly catch 500 errors and convert to the proper GaaSException response
-UI: Have better Error Response conversion that can handle any error response body from the rest layer

**Comment by go159lab** [comment]
add the fix of 500 error response
