### ISSUE TITLE
GaaS API Return Problems For Each Graph

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#77]
As a User of the API - I want to have any problems visible
So that - I don't have to see the Gaffer resource from the terminal or console if any problems exist, associated with my Gaffer instances

Some `kind: Gaffer`'s return errors in the k8s resource like the one below:
```
status:
  problems:
    - |
      Error: cannot re-use a name that is still in use
```
Example causes can be Accumulo password not set or reusing same unique names

This can be accessed from `new Gaffer().getStatus().getProblems()`. Add this to the API response so that Users of the API have this visibility

**Comment by go159lab** [comment]
add functionality to return problems for each graph.

for instance the response may look like this below.

**{
        "graphId": "testgraph4",
        "description": "Test Graph Description",
        "url": "http://testgraph4-kai-dev.apps.my.kubernetes.cluster/rest",
        "status": "UP",
        "problems": [
            "Error: cannot re-use a name that is still in use\n",
            "Error: cannot re-use a name that is still in use\n",
            "Error: cannot re-use a name that is still in use\n"
        ]
    },**
