### ISSUE TITLE
Move components to `gaas-common`

### ISSUE THREAD

**Issue by r32575** [gchq/gaffer-experimental#83]
There is a reference to `gaffer-controller` in `gaas-rest` when there **should not be**. When sharing the models across both the modules (`GafferSpec` etc) they should be in `gaas-common` which at present isn't being utilised. As `gaffer-controller` and `gaas-rest` through Kubernetes they should not refer to each other in their relative poms.

**Comment by go159lab** [comment]
move components to gaas-common and done refactoring gas-rest and gaffer-controller. all unit test passed.

**Comment by rocky341** [comment]
This has been added to the #86 PR
