### ISSUE TITLE
UI - Change StoreType enums to correct values accepted by the API

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#87]
Bug:
Change the enum string values to the same string enum values accepted by the API

Fix:
Currently the store type string value is sent in camel case format - needs to be changed to all caps

**Comment by rocky341** [comment]
Once #86 is merged in it should be in camel case to reflect the changes in the API.

**Comment by rocky341** [comment]
I believe this ticket is redundant as per #95, #99, and #79
