### ISSUE TITLE
Add a /metrics Endpoint for some Basic Metric Counters - Use app.properties Flag To Turn It On/Off

### ISSUE THREAD

**Issue by macenturalxl1** [gchq/gaffer-experimental#89]
As a User - I want to have metrics for how many Create Graphs Requests made
So that - I can have the number

Requirement:
- Add a /metrics endpoint to Gaas controller
- Add a cardinaltiy counter to Add Graph requests
- Store the counter in memory 
- Send the counter int back
- add management endpoints web exposure include to switch on/off promethous

**Comment by K-itKat20** [comment]
The metrics branch includes the following metrics for all the services (Auth, CreateGraph, DeleteGraph, GetGaffer, GetNamespace): total count for each service, time in seconds, time in seconds (count), time in seconds (max), time in seconds(sum)
